### ISSUE TITLE
Auth.js component

### ISSUE THREAD

**Issue by pyxarez** [mixalezhnev/schoolmath#3]
![auth js](https://cloud.githubusercontent.com/assets/23152279/24549011/7afb5d64-1628-11e7-8e39-1d0d111c2b86.png)
Может как-то так?
![newauth js](https://cloud.githubusercontent.com/assets/23152279/24549227/66a9da88-1629-11e7-86d5-c857c829c5cc.png)

**Comment by mixalezhnev** [comment]
Этот компонент еще планируется разрабатывать, это временно. Второй вариант разумеется лучше
