### ISSUE TITLE
Stateless components and other strange things

### ISSUE THREAD

**Issue by pyxarez** [mixalezhnev/schoolmath#4]
![btn](https://cloud.githubusercontent.com/assets/23152279/24549356/f0f1cfe8-1629-11e7-812b-fc54de6ab487.png) 
![header](https://cloud.githubusercontent.com/assets/23152279/24549447/54ee7032-162a-11e7-97b2-84e1145d94ba.png)
Вместо классов лучше функции(наверно).
Та же тема с [Mission](https://github.com/mixalezhnev/schoolmath/blob/development/src/components/Mission.js), [Navigation](https://github.com/mixalezhnev/schoolmath/blob/development/src/components/Navigation.js), [Practice](https://github.com/mixalezhnev/schoolmath/blob/development/src/components/Practice.js),
[Progress](https://github.com/mixalezhnev/schoolmath/blob/development/src/components/Progress.js) и [Section](https://github.com/mixalezhnev/schoolmath/blob/development/src/components/Section.js)
Всё туда #2, #3 
Зачем этот контейнер?
![navitemcont](https://cloud.githubusercontent.com/assets/23152279/24549677/7c119332-162b-11e7-8ed8-f7a03f847c55.png)
Эту конструкцию можно упростить, я тебе рассказывал
![overview](https://cloud.githubusercontent.com/assets/23152279/24549694/9c3692b6-162b-11e7-8822-0479d3950ba5.png)
api советуют выносить в отдельное место, здесь вызывать
![fetch](https://cloud.githubusercontent.com/assets/23152279/24550390/db3d2a08-162e-11e7-880c-11e91c746e8b.png)
Кстати, как на счёт того, чтобы говорить пользователю о том, что статьи не прогрузились, а не просто выводить в консоль?

**Comment by mixalezhnev** [comment]
> Кстати, как на счёт того, чтобы говорить пользователю о том, что статьи не прогрузились, а не просто выводить в консоль?

Это пока далеко, пока чтобы работало, прогрессивное улучшение. Вообще нужно уделить внимание обработке всемозможных ошибок и как реагировать правильно на них
